# Copyright (C) 2025 AIDC-AI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Post data models for image-text post generation.
"""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import List, Optional


@dataclass
class PostFrame:
    """Single frame information for image-text post."""

    index: int
    image_prompt: str
    caption: str
    image_path: Optional[Path] = None


@dataclass
class PostContent:
    """Structured post content generated by LLM."""

    title: str
    body: str
    hashtags: List[str]
    frames: List[PostFrame]


@dataclass
class PostGenerationResult:
    """Post generation result."""

    task_id: str
    output_dir: Path
    content: PostContent
    created_at: datetime = field(default_factory=datetime.now)
